package config

import (
	"fmt"
	"strings"
	"testing"
)

// TestPresetsDifferOnlyInThePrefix: the shipped presets are one grammar over
// two prefix vocabularies (DESIGN §2, t-h9y7), and rulings land in every
// preset on that promise. Outside the lines a prefix forces apart — the
// header and style label, the vocabulary note, the template's form line, the
// first pattern's comment and regex, and the amend! body regex that mirrors
// it — each preset is held byte for byte to gemoji, so a correction that
// lands in one preset alone fails here. The packages paragraph drifted
// exactly that way while it was typed into each preset (#228). What the
// masked lines must still agree on is TestPresetsShareOneGrammar's to assert.
//
// bite-exempt: ratifies the parity the tree already has, so it cannot fail
// against pre-PR source; the mutation-ledger rows
// presets-drift-outside-the-prefix.patch and
// presets-grammar-grows-a-key-in-one-preset.patch are what prove it still
// bites.
func TestPresetsDifferOnlyInThePrefix(t *testing.T) {
	// Each region must be found exactly once: a mask that matched nothing
	// compares nothing, and one whose end marker is gone swallows the rest of
	// the file — either way the comparison would pass on no evidence.
	regions := []string{"header", "style", "vocabulary note", "template form", "first pattern", "amend! body"}
	mask := func(t *testing.T, name string) string {
		t.Helper()
		data, ok := Preset(name)
		if !ok {
			t.Fatalf("Preset(%s) missing", name)
		}
		found := map[string]int{}
		var out []string
		in, seenFirst := "", false
		for l := range strings.SplitSeq(string(data), "\n") {
			switch {
			case in == "vocabulary note":
				if !strings.HasPrefix(l, "# The template is for humans") {
					continue
				}
				found[in]++
				in = ""
				out = append(out, "<vocabulary note>")
			case in == "template form":
				found[in]++
				in = ""
				out = append(out, "<template form>")
				continue
			case in == "first pattern":
				// Only the entry's comment and its regex carry the prefix; any
				// other key it gains (a warn, a fixed sigil, a skip) changes the
				// grammar's verdict and is compared like every other line.
				switch {
				case strings.HasPrefix(l, "#"):
					continue
				case strings.HasPrefix(l, "pattern = "):
					found[in]++
					out = append(out, "<first pattern>")
					continue
				case l == "":
					in = ""
				}
			case l == "# glyph.toml — generated by `glyph init --"+name+"`":
				found["header"]++
				out = append(out, "<header>")
				continue
			case l == `style = "`+name+`"`:
				found["style"]++
				in = "vocabulary note"
				out = append(out, "<style>")
				continue
			case l == "template = '''":
				in = "template form"
			case l == "[[patterns]]" && !seenFirst:
				seenFirst = true
				in = "first pattern"
			case strings.HasPrefix(l, "pattern = '^amend! "):
				found["amend! body"]++
				out = append(out, "<amend! body>")
				continue
			}
			out = append(out, l)
		}
		for _, r := range regions {
			if found[r] != 1 {
				t.Fatalf("preset %s: the %s region was found %d times, want once — the mask no longer fits the file, so the comparison would prove nothing", name, r, found[r])
			}
		}
		return strings.Join(out, "\n")
	}

	want := mask(t, "gemoji")
	for _, name := range PresetNames() {
		if got := mask(t, name); got != want {
			t.Errorf("preset %s differs from gemoji outside its prefix-bearing lines, first at %q — a change to the shared grammar lands in every preset", name, firstDiffLine(got, want))
		}
	}
}

// TestPresetsShareOneGrammar asserts by behaviour what the lines
// TestPresetsDifferOnlyInThePrefix masks must still agree on, in every
// shipped preset. Those lines carry the classes the presets share inside
// their prefix — the scope class and the five-sigil class, in the grammar and
// again in the amend! body — so each preset's subject form runs over every
// sigil and a scope of each shape the class admits (none, a word, a digit, a
// hyphen): the grammar claims each at patterns[0] with that sigil and scope,
// the whole first line as its subject and no warning, and an amend! whose
// body is that subject is claimed unlandable. A subject with no sigil is a
// violation whatever its prefix says (a conventional type included), and a
// BREAKING CHANGE footer moves nothing — it neither raises a sigil'd subject
// nor rescues a sigil-less one, because the sigil is the only version signal
// (t-h9y7, DESIGN §2). The samples are the whole guard on those lines: a
// ruling that changes a shared class adds its sample here, for every preset.
// A preset added without its messages here fails, so a new grammar has to
// say what these look like in it.
//
// bite-exempt: ratifies the behaviour the tree already has, so it cannot fail
// against pre-PR source; the mutation-ledger rows
// conventional-preset-reads-the-type-as-the-version.patch,
// presets-read-the-breaking-change-footer.patch,
// presets-scope-class-drifts-in-one-preset.patch and
// presets-amend-body-drifts-in-one-preset.patch are what prove it still bites.
func TestPresetsShareOneGrammar(t *testing.T) {
	grammar := map[string]struct {
		form      string   // a sigil'd subject: %[1]s is "(scope)" or "", %[2]s the sigil
		sigilless []string // subjects no pattern may claim
		patch     string   // a patch subject, matched over a BREAKING CHANGE footer
	}{
		"gemoji":       {":sparkles:%s%s add x", []string{":sparkles: add x", ":bug:(b) fix b"}, ":bug:~ fix b"},
		"conventional": {"feat%s%s: add x", []string{"feat: add x", "fix(b): fix b"}, "fix~: fix b"},
	}
	const footer = "\n\nBREAKING CHANGE: b is gone"
	for _, name := range PresetNames() {
		t.Run(name, func(t *testing.T) {
			g, ok := grammar[name]
			if !ok {
				t.Fatalf("preset %q has no messages here: say what its grammar's subjects look like", name)
			}
			data, _ := Preset(name)
			cfg := mustLoad(t, string(data))

			target := fmt.Sprintf(g.form, "", "~")
			for _, scope := range []string{"", "x", "a1", "api-v2"} {
				paren := ""
				if scope != "" {
					paren = "(" + scope + ")"
				}
				for _, sigil := range []Sigil{SigilNone, SigilPatch, SigilMinor, SigilMajor, SigilPromote} {
					subject := fmt.Sprintf(g.form, paren, string(sigil))
					m, err := cfg.Match(subject + "\n\nwhy it was made")
					if err != nil || !m.Matched || m.PatternIndex != 0 || m.Skip || m.Warn != "" ||
						m.Sigil != sigil || m.Groups["scope"] != scope || m.Groups["subject"] != subject {
						t.Errorf("%q = %+v (err %v), want the grammar at patterns[0] reading %c and scope %q, the whole first line as its subject, and no warning", subject, m, err, sigil, scope)
					}
					amend := "amend! " + target + "\n\n" + subject
					if a, err := cfg.Match(amend); err != nil || a.Matched || a.Unlandable == "" {
						t.Errorf("%q = %+v (err %v), want the amend! claim: its body opens as the grammar's subject, so the hook lets git's message through and the range gates refuse it", amend, a, err)
					}
				}
			}
			for _, s := range g.sigilless {
				for _, msg := range []string{s, s + footer} {
					if v := cfg.Lint(msg, "akira"); v.OK || v.Excluded || v.Warn != "" {
						t.Errorf("Lint(%q) = %+v, want a violation: no sigil was written, and neither a prefix nor a footer is one", msg, v)
					}
				}
			}
			if m, err := cfg.Match(g.patch + footer); err != nil || !m.Matched || m.Skip || m.Sigil != SigilPatch {
				t.Errorf("%q = %+v (err %v), want the subject's ~: a footer is prose, not a sigil", g.patch+footer, m, err)
			}
		})
	}
}
